### ISSUE TITLE
Initialize various repositories

### ISSUE THREAD

**Issue by nfebe** [whilesmart/trakli#4]
# Public voting

A group of about 6 of us are voting on what to use for this hackathon.

## Web service

-  Laravel
-  Nest.js
-  Express
-  Symphony 

## UI
-  Vue.js
-  Nuxt.js
-  React.js
-  Svelte.js
-  Vanilla

## Mobile

- Flutter
- Kotlin - Multiplatform
- React
- Vue

**Comment by nfebe** [comment]
- Webservice vote => Laravel
- UI => Nuxt.js
- Mobile => Flutter

**Comment by aanorbel** [comment]
### Web Service
Laravel https://laravel.com/
### UI
Nuxt.js https://nuxt.com/ 
### Mobile
Flutter https://flutter.dev/

**Comment by Flovet-stack** [comment]
- Webservice vote => Laravel
- UI => NextJs
- Mobile => Flutter

**Comment by DriZy** [comment]
## Web Service 
Express

## UI
React.js

## Mobile
Flutter

**Comment by nfebe** [comment]
### Task assignments

- [ ] Initialize flutter repo : https://github.com/whilesmart/trakli-mobile - @austin047 
- [ ] Initialize webservice repo - @Fenn-CS 
- [ ] Initialize ui repo - @Flovet-stack 
- [ ] Initialize infra (`this.me`) - @aanorbel

**Comment by nfebe** [comment]
### Basic standards for initialization

- Include linting for your repositories 
- Include jobs to check for linting
- Include job to run tests even if just default tests
- Include job to build successful
- Include custom readme
